### ISSUE TITLE
Safe automated driving

### ISSUE THREAD

**Issue by klarasve** [DIT112-V21/group-02#15]
5.1.1 The system should intelligently maneuver the car so that the car will arrive safely
3.3 As a user I want to visually see the object detection so that I can avoid these objects
3.1 As a user in easy mode, I want my car to automatically avoid obstacles so that I do not have to manually avoid them.

Acceptance criteria: This is a combination of 5.1, 3.1 and 3.2. Therefore the acceptance criteria for this is that the vehicle can reach a location guaranteeing a certain level of health while avoiding obstacles during a self-driving course.

*Refers to FR 1.1

**Comment by klarasve** [comment]
Is this doable or do we want to scrap this? Also: Should this be broken down into multiple issues?

**Comment by MrJonte** [comment]
out of scope
