### ISSUE TITLE
impossibility calculations

### ISSUE THREAD

**Issue by drakeaxelrod** [DIT112-V21/group-02#18]
7.3 As a user I don't want to waste my time trying to go places that I cant reach within a realistic timeframe. Therefore the system should provide feedback if the position is impossible to reach in a specified amount of time.

Acceptance criteria: The system successfully calculates time it would take to travel distance using UCS and displaying to user.

*Refers to FR: 1.17

**Comment by VernitaJ** [comment]
This issue has become redundant as we won't be implementing a drive-to-location feature.
