### ISSUE TITLE
Data base set up

### ISSUE THREAD

**Issue by MrJonte** [DIT112-V21/group-02#24]
4.6 As a user I want the time for the races I've completed to be stored and showcased so I can compare and brag about it to my friends.

Acceptance criteria: User race times is stored and displayed in the software

FR: 1.18

**Comment by worldisyoursdude** [comment]
Racing data can be, but isn't limited to:

- Lap time
- Positions
- Racer (player) names
- Map name
- Car (s) used (see #42 and #31)

Any other input on what can and should be stored would be appreciated :D

**Comment by VernitaJ** [comment]
Database setup backend completed, implemented, and merged.
