### ISSUE TITLE
Racing Against Friends

### ISSUE THREAD

**Issue by drakeaxelrod** [DIT112-V21/group-02#31]
4.5 As a user I would like to be able to race against my friends in the same environment so that I can prove my superiority.

Acceptance criteria - python program to auto compile and start new cars

**Comment by worldisyoursdude** [comment]
Mentioned this in #42 , would love some input. Depends primarily on whether y'all can actually implement different models (one per player, perhaps?) or if we should just use one model and randomize textures.

**Comment by MrJonte** [comment]
We cant really implement several cars so the raising against friends will be implemented with the database leader board.
