### ISSUE TITLE
Configure textures in new environment.

### ISSUE THREAD

**Issue by Axel-J-L** [DIT112-V21/group-02#38]
Update textures for the buildings in the new environment.

**Comment by worldisyoursdude** [comment]
See #41. Should textures be made specifically for each building, or shall we just create general textures and add them to specific models?

**Comment by Axel-J-L** [comment]
I think we should create specific textures for specific buildings, as you noted in #41, separating the parts of the buildings would in my opinion the way to go if we create textures for specific objects.

**Comment by worldisyoursdude** [comment]
Textures come bundled with our models, as well as pre-made models. Closing this as this is considered "done" in the sense that not much more could be done here.
