### ISSUE TITLE
User Interface

### ISSUE THREAD

**Issue by VernitaJ** [DIT112-V21/group-02#4]
2.1 As a user, I want to be able to use a simple remote control to control the car, so that I don’t have to spend a lot of time figuring out how to use it.

V2 
Acceptance criteria: User interface for car controls

V1 
Acceptance Criteria: Mobile app control with buttons to go forward, backward, turn left, turn right.

*Referes to FR 1.3

**Comment by VernitaJ** [comment]
Initial design update
![unknown](https://user-images.githubusercontent.com/55649851/114400780-9adb4280-9ba2-11eb-9b81-1903c6539e7a.png)

**Comment by platisd** [comment]
Ambitious, I like it! :D
