### ISSUE TITLE
New car models

### ISSUE THREAD

**Issue by worldisyoursdude** [DIT112-V21/group-02#42]
Current car model is far too basic, and is incompatible with multiplayer  ( see #31 ).

Shall we use multiple models? Or just one model with multiple textures? If it's the latter, please create a new issue for the textures.

**Comment by Axel-J-L** [comment]
Yes I agree, I did find a asset library that seems to be fitting for this purpose. I think applying different textures to that model wouldn't pose to much of a problem .

**Comment by worldisyoursdude** [comment]
Awesome. How would the textures be created though? Esp because the model is so idiosyncratic, we would probably have to start from scratch.
