### ISSUE TITLE
Joystick on the racing page

### ISSUE THREAD

**Issue by VernitaJ** [DIT112-V21/group-02#43]
6.1 As a user, I would like to control the car through multiple different ways, such as a keyboard or a discord bot, so that I can test the car in numerous ways:

We need a joystick interface that is simple to use in order to control the drive. This joystick would most likely be used on a mobile, whilst the keyboard would be the main input for the computer user.

Acceptance criteria: Functional joystick on webapplication.

FR: 1.19

**Comment by worldisyoursdude** [comment]
Godot has controller/joystick support built in. Why not utilize those while treating the phone as a controller/joystick of sorts? Interpreting the phone as a joystick using the app should be easier than coding it in.

**Comment by VernitaJ** [comment]
If I'm not mistaken, the joystick in godot still needs to be coded. So in that case it would be a similar amount of effort, but for usability it would be beneficial for our user to have the joystick on their screen.

**Comment by worldisyoursdude** [comment]
Actually, we can just implement the controls directly in the Godot engine! It's just mapping the controls on the phone, and somehow connecting them that's difficult.

**Comment by VernitaJ** [comment]
So does that mean that either way you need an interface on the phone to control the car in godot?

**Comment by worldisyoursdude** [comment]
Well, yeah. I just mean that it's simple from the engine side of things. We'll still need an interactive interface and to map controls on the phone app.
