### ISSUE TITLE
Racing difficulty

### ISSUE THREAD

**Issue by MrJonte** [DIT112-V21/group-02#7]
4.1 As a user, I want to be able to choose the racing difficulty, so that I can have the ability to improve.
4.1.1 As a user , I want to be able to up the difficulty to challenge myself when I want to.

Acceptance criteria: Racing environment (obstacle avoidance etc.) changes based on difficulty level

FR: 1.13

**Comment by VernitaJ** [comment]
This idea has shifted from implementing difficulty using automation to applying differences in speed to make it easier/harder for the driver to win.

**Comment by VernitaJ** [comment]
Difficulty is now working as intended, with the chosen difficulty level sent to the backend in order for the race map to be more/less difficult to win.
