### ISSUE TITLE
Speed boost

### ISSUE THREAD

**Issue by MrJonte** [DIT112-V21/group-02#9]
4.2 As a user, I want to be able to boost the speed on the car, so that I can gain a lead on my opponent.

Acceptance criteria: The smart-car gains a speedboost when driving over a marked area

FR: 1.6

**Comment by MrJonte** [comment]
speed bost implemented in the discord bot. issue closed

**Comment by VernitaJ** [comment]
If we are able to bypass the speed limit currently set by smce, we'll implement this.
